on:
  schedule:
    - cron: 0 0 * * 1   # midnight every Monday
  workflow_dispatch:
  workflow_call:

jobs:
  check-links:
    permissions:
      contents: read
    name: Linkspector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: info
          show_stats: false
          fail_level: warning
          config_file: .linkspector.yml
